package it.patric.cittaexp.playersgui;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;
import java.util.Locale;
import java.util.logging.Logger;
import net.william278.husktowns.town.Privilege;

public final class CittaExpTownRoleGovernanceService {

    private static final List<RoleSpec> ROLE_SPECS = List.of(
            new RoleSpec(1, "Residente", List.of(
                    Privilege.DEPOSIT,
                    Privilege.CHAT,
                    Privilege.CLAIM_PLOT,
                    Privilege.SPAWN
            )),
            new RoleSpec(2, "Artigiano", List.of(
                    Privilege.TRUSTED_ACCESS,
                    Privilege.SET_FARM,
                    Privilege.SET_PLOT,
                    Privilege.MANAGE_PLOT_MEMBERS
            )),
            new RoleSpec(3, "Mercante", List.of(
                    Privilege.INVITE,
                    Privilege.SET_GREETING,
                    Privilege.SET_FAREWELL
            )),
            new RoleSpec(4, "Economista", List.of(
                    Privilege.WITHDRAW,
                    Privilege.LEVEL_UP,
                    Privilege.VIEW_LOGS
            )),
            new RoleSpec(5, "Funzionario", List.of(
                    Privilege.CLAIM,
                    Privilege.UNCLAIM
            )),
            new RoleSpec(6, "Prefetto", List.of(
                    Privilege.SET_SPAWN,
                    Privilege.SPAWN_PRIVACY,
                    Privilege.MANAGE_RELATIONS
            )),
            new RoleSpec(7, "Stratega", List.of(
                    Privilege.DECLARE_WAR
            )),
            new RoleSpec(8, "Magistrato", List.of(
                    Privilege.SET_RULES,
                    Privilege.EVICT
            )),
            new RoleSpec(9, "Vice", List.of(
                    Privilege.PROMOTE,
                    Privilege.DEMOTE,
                    Privilege.RENAME,
                    Privilege.SET_COLOR
            )),
            new RoleSpec(10, "Capo", List.of(
                    Privilege.SET_BIO
            ))
    );

    private final Logger logger;
    private final File rolesFile;

    public CittaExpTownRoleGovernanceService(
            Logger logger,
            File rolesFile
    ) {
        this.logger = logger;
        this.rolesFile = rolesFile;
    }

    public void ensureGovernedRoles() {
        String desired = desiredYaml();
        String current = readCurrent();
        if (normalize(current).equals(normalize(desired))) {
            logger.info("[players-gui] roles.yml gia allineato alla ladder CittaEXP.");
            return;
        }
        try {
            File parent = rolesFile.getParentFile();
            if (parent != null) {
                Files.createDirectories(parent.toPath());
            }
            Files.writeString(rolesFile.toPath(), desired, StandardCharsets.UTF_8);
            logger.info("[players-gui] roles.yml riallineato alla ladder CittaEXP.");
        } catch (IOException exception) {
            logger.severe("[players-gui] impossibile scrivere roles.yml: " + exception.getMessage());
            return;
        }
        logger.warning("[players-gui] roles.yml e stato aggiornato senza forzare reload di HuskTowns."
                + " Il nuovo assetto ruoli verra applicato al prossimo riavvio sicuro del server.");
    }

    private String readCurrent() {
        if (!rolesFile.exists()) {
            return "";
        }
        try {
            return Files.readString(rolesFile.toPath(), StandardCharsets.UTF_8);
        } catch (IOException exception) {
            logger.warning("[players-gui] impossibile leggere roles.yml corrente: " + exception.getMessage());
            return "";
        }
    }

    private static String normalize(String value) {
        return value == null ? "" : value.replace("\r\n", "\n").trim();
    }

    private String desiredYaml() {
        StringBuilder builder = new StringBuilder();
        builder.append("# Generated by CittaEXP. Manual edits may be overwritten.\n");
        builder.append("names:\n");
        for (RoleSpec spec : ROLE_SPECS) {
            builder.append("  '").append(spec.weight()).append("': ").append(spec.name()).append('\n');
        }
        builder.append("roles:\n");
        for (RoleSpec spec : ROLE_SPECS) {
            builder.append("  '").append(spec.weight()).append("':\n");
            for (Privilege privilege : spec.privileges()) {
                builder.append("    - ").append(privilege.id().toLowerCase(Locale.ROOT)).append('\n');
            }
        }
        return builder.toString();
    }

    private record RoleSpec(int weight, String name, List<Privilege> privileges) {
    }
}
