package it.patric.cittaexp.permissions;

public enum TownMemberPermission {
    ITEM_VAULT_OPEN,
    ITEM_VAULT_DEPOSIT,
    ITEM_VAULT_WITHDRAW,
    ITEM_VAULT_MANAGE_PERMISSIONS,
    CITY_SHOP_CREATE,
    CITY_SHOP_CONFIGURE,
    CITY_SHOP_DESTROY,
    CITY_DEFENSE_MANAGE,
    CITY_DEFENSE_SPEND,
    MOB_INVASION_START,
    MOB_INVASION_MANAGE,
    CITY_CHALLENGES_MANAGE,
    CITY_CHALLENGES_REDEEM,
    CITY_EVENTS_SUBMIT
}
